### ISSUE TITLE
Skip files that are most likely binary

### ISSUE THREAD

**Issue by spenserblack** [spenserblack/gengo#10]
For example, this tool could check for file signatures/magic bytes.

## Promising crates

- [infer](https://crates.io/crates/infer)
- [mime_guess](https://crates.io/crates/mime_guess)

**Comment by Byron** [comment]
Actually I'd recommend using `.gitattributes` for this as well. Most people will probably use it to mark their binaries.

Further, `gix-filter` implements the 'is-binary' check that `git` uses - it's very simple and fast, and I could expose it. Right now it's private.

**Comment by spenserblack** [comment]
Using `.gitattributes` is definitely tempting, but I don't think it's the way to go, for 2 reasons:
1. A lot of JS projects check in minified files and use `path/to/minified/* binary`. Check out [yarn's recommended `.gitattributes`](https://yarnpkg.com/getting-started/qa#which-files-should-be-gitignored), for example. These files are marked as binary for git, but in reality they are text files, and I'd want gengo to analyze them. For yarn's case, they would be vendored JavaScript.
2. Plenty of binary files *aren't* marked as such in `.gitattributes`, instead relying on Git's ability to infer if a file if text is binary. This perhaps isn't that important for CLI tools, but I think linguist added it for the variety of types of repositories on GitHub. Many git beginners will check in files that (IMO) they shouldn't, like `a.out` or `my-project.exe`. There are also repositories that aren't code, but assets, like image collections.

However, `is_binary` looks like *exactly* what could be needed :heart:

**Comment by spenserblack** [comment]
Based on some quick skimming of its dependencies, I believe [this is the relevant code](https://github.com/brianmario/charlock_holmes/blob/3f4f57cfbee6dcd11941f54f9d4da0ebc1402421/ext/charlock_holmes/encoding_detector.c#L61-L130) for how Linguist detects if a file is binary (also if the file is just plain too big it's considered binary).

**Comment by spenserblack** [comment]
Stumbled on a PR comment in CharlockHolmes that states that git only reads the first 8000 bytes, but this was not sufficient because some files (a few Adobe file types IIRC) start out as text but are followed by binary content. Overall that should be considered binary, but scanning the first 8000 bytes apparently made it look like a text file.

**Comment by Byron** [comment]
That's interesting, thanks for sharing! Git definitely has very simple heuristics compared to linguist, which is probably made to deal with most files without any configuration, and over time more and more special cases were added to deal with that diversity.
