### ISSUE TITLE
Parallelize

### ISSUE THREAD

**Issue by spenserblack** [spenserblack/gengo#155]
As mentioned in https://github.com/o2sh/onefetch/pull/1152#issuecomment-1703871936, this has potential for for performance improvements.

cc @Byron

**Comment by spenserblack** [comment]
I'll admit that, while I'm familiar with concurrency/parallelization (more in Go than Rust), doing it *well* can be a different story :laughing:

There's a joke in Go that goes something like this:
```go
// Beginner
func SumGroups(groups [][]int) []int {
	sums := make([]int, len(groups))
	for i, group := range groups {
		for _, n := range group {
			sums[i] += n
		}
	}
	return sums
}

// Experienced
func SumGroups(groups [][]int) []int {
	sums := make([]int, len(groups))
	sumsch := make(chan int, len(groups))
	for _, group := range groups {
		go func(ch chan int, group []int) {
			sum := 0
			for _, n := range group {
				sum += n
			}

			ch <- sum
		}(sumsch, group)
	}

	for i := range sums {
		sums[i] = <-sumsch
	}
	close(sumsch)
	return sums
}

// Rob Pike
func SumGroups(groups [][]int) []int {
	sums := make([]int, len(groups))
	for i, group := range groups {
		for _, n := range group {
			sums[i] += n
		}
	}
	return sums
}
```

So I'd appreciate tips on the best way to do this. My instincts say the threads should be batched. Or is it really fine to spawn a thread for each file to be analyzed?

**Comment by Byron** [comment]
I think it *should* be trivial and I will add a commit for parallelization as well. That parallelization will be quite optimal as well, letting X threads work on one file each, but without communication overhead.
