### ISSUE TITLE
Handle submodules

### ISSUE THREAD

**Issue by spenserblack** [spenserblack/gengo#163]
With #157, submodules are now traversed. As mentioned in https://github.com/spenserblack/gengo/pull/157#issuecomment-1706517206, I'm of the opinion that submodules should be vendored by default, defining "vendored" as "files that are not from this repository that are distributed with it."

cc @Byron

**Comment by spenserblack** [comment]
:thinking: After some quick testing, I've found that submodule files are not analyzed unless
- The repo is not bare
- The submodules have been initialized (`git submodule update --init`)

Which in hindsight is obvious, I guess :laughing:

**Comment by Byron** [comment]
> * The submodules have been initialized (`git submodule update --init`)

Yes, and to be extra-precise, it's implemented in a way that doesn't care whether it's initialized, it only cares about a submodule repository being present so it uses what's there. `--init` means it will drop some configuration values into the superproject's `.git/config`, but that configuration doesn't matter to `gengo` and I don't think it has to matter. However, if one wanted to be a perfect citizen and act exactly like git would, one would only act on [active submodules](https://docs.rs/gix/0.52.0/gix/struct.Submodule.html#method.is_active).
