### ISSUE TITLE
:jack_o_lantern: Hacktoberfest: Help add (programming/data/etc.) language support!

### ISSUE THREAD

**Issue by spenserblack** [spenserblack/gengo#221]
First things first: No Rust knowledge required! All you need is some basic knowledge on a language that this project doesn't support. And not just programming languages! Data languages (like JSON or CSV), markup (HTML), and others are also welcome.

Basically, you need to modify `gengo/languages.yaml` and provide the following:
- What's the name of the language
- Provide a color to associate the language
- Choose a category that best fits the language
- Are there any file extensions associated with the language? E.g. `js` for JavaScript.
- Are there any filenames associated with the language? E.g. `Dockerfile` for Docker.

There are [plenty of pull requests](https://github.com/spenserblack/gengo/pulls?q=is%3Apr+label%3Anew-language+) that you can use as an example.

View `docs/CONTRIBUTING.md` for more details.

**Comment by vinayakhegde1** [comment]
Hello @spenserblack can i work on this I would like to add

**Comment by spenserblack** [comment]
Nope, you don't need to install anything! Any testing is [run automatically when you make a PR](https://github.com/spenserblack/gengo/blob/8bdfd88b9eb0eebc0e586a4ae30a8ca15efa3141/.github/workflows/ci.yml). So, yeah, you just need to add a new language to the file.

**Comment by vinayakhegde1** [comment]
@spenserblack added swift
