### ISSUE TITLE
Use `.gitattributes` from rev?

### ISSUE THREAD

**Issue by spenserblack** [spenserblack/gengo#31]
Right now, gengo uses the `.gitattributes` file from the filesystem. E.g. changes to `.gitattributes` that haven't been committed can affect the file attributes (vendored, detectable, etc.).

github-linguist uses the `.gitattributes` *of the analyzed rev.* Until you commit your changes to `.gitattributes`, it will not affect github-linguist.

Right now I don't know which is preferable.

**Comment by Byron** [comment]
As worktree files aren't read currently, I think it's more precise to use `.gitattributes` from `rev` only. Once the worktree is used, it should do the worktree first, then fallback to `rev`.

**Comment by Byron** [comment]
On the matter of `.gitattributes`, should we not also support `linguist-` prefixed attributes? I have a feeling that it will take a long time until people add `gengo-` prefixed attributes to their repos.

**Comment by spenserblack** [comment]
> On the matter of `.gitattributes`, should we not also support `linguist-` prefixed attributes? I have a feeling that it will take a long time until people add `gengo-` prefixed attributes to their repos.

I definitely see the argument for using `linguist-*`. There's certainly a desire to get Gengo to work more "out of the box" by supporting these. Besides my comment here https://github.com/spenserblack/gengo/pull/157#issuecomment-1704320483, I'll say that I'm fine to ask (force?) users to use `gengo-*` because these overrides should be the rare exception, and not the rule.
